name:                Morphology-PT
version:             0.1.0.0
github:              "jjunho/Morphology-PT"
license:             BSD3
author:              "Juliano Paiva Junho"
maintainer:          "jjunho@gmail.com"
copyright:           "Copyright 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Morphology of the Portuguese language
category:            Linguistics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jjunho/Morphology-PT#readme>

dependencies:
- base >= 4.7 && < 5
- text
- hspec

library:
  source-dirs: src

executables:
  Morphology-PT-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Morphology-PT

tests:
  Morphology-PT-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Morphology-PT
